### ISSUE TITLE
have_tag not available in the latest version `0.7.0`

### ISSUE THREAD

**Issue by NafaaBout** [kucaahbe/rspec-html-matchers#34] opened 2015-02-22 13:09 UTC
I get this error with the latest version `0.7.0`, but it does not show up with the previous version `0.6.1`

       Failure/Error: expect(page).to have_tag('a', text: article.author_name, with:{ href:                   author_path(article.author)})
        expected #<Capybara::Session:0x00000005fc5d78> to respond to `has_tag?`

**Comment by kucaahbe** [comment] 2015-02-22 15:05
Probably duplicate of #33
[this should help](https://github.com/kucaahbe/rspec-html-matchers#install)

**Closed by kucaahbe** 2015-02-22 15:05 UTC
